# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-16 22:22
from __future__ import unicode_literals

from django.db import migrations
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='state',
            field=django_fsm.FSMField(choices=[('CREATED', 'Создан'), ('BOUGHT', 'Оплачен'), ('IN_USE', 'Используется'), ('USED', 'Использован')], max_length=50),
        ),
    ]
